# Generated by Django 3.2.7 on 2021-09-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('surname', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=10000)),
                ('password', models.CharField(max_length=10000)),
            ],
        ),
    ]
