# Generated by Django 3.2.7 on 2021-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expenses',
            field=models.CharField(default='0', max_length=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='savings',
            field=models.CharField(default='0', max_length=100000),
        ),
    ]
