# Generated by Django 3.2.7 on 2021-09-04 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210904_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_earning_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 15, 50, 13, 134430)),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_earnings',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='savings',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
