# Generated by Django 3.2.7 on 2021-09-04 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20210904_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('model_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_insta', models.CharField(blank=True, max_length=30)),
                ('expenses', models.CharField(default='0', max_length=100000)),
                ('savings', models.CharField(default='', max_length=100000)),
                ('monthly_earnings', models.CharField(default='', max_length=100000)),
                ('last_earning_add', models.DateTimeField(default=datetime.datetime(2021, 9, 4, 16, 46, 44, 37641))),
                ('today', models.DateTimeField(default=datetime.datetime(2021, 9, 4, 16, 46, 44, 37641))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
