# Generated by Django 3.2.7 on 2021-09-04 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210904_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='monthly_earnings',
            new_name='income',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_earning_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 18, 32, 24, 687002)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 18, 32, 24, 687002)),
        ),
    ]
