# Generated by Django 3.2.7 on 2021-09-04 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210904_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clothing_expenses',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='electricity_expenses',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='food_expenses',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='mics_expenses',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='rent_expenses',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='transport_expenses',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='water_expenses',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_earning_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 22, 56, 58, 700585)),
        ),
        migrations.AlterField(
            model_name='user',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 22, 56, 58, 700585)),
        ),
    ]
